[package]
name = "kozo"
version = "0.1.0"
edition = "2021"

[dependencies]
hmac-sha256 = "1.1.7"
nohash-hasher = "0.2.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
insta = "1.29.0"

[build-dependencies]
kiki = "7"
walkdir = "2"
sha256 = "1.1.4"
